### 그룹 
### 1. 그룹 등록
POST http://localhost:3000/api/groups
Content-Type: application/json

{
  "title": "새로운 그룹",
  "img": "https://example.com/new-group.jpg",
  "description": "새로운 그룹입니다.",
  "isPublic": true,
  "password": "group1234"
}

### 2. 그룹 수정
PUT http://localhost:3000/api/groups/66fe495af847596339501bcb
Content-Type: application/json

{
  "title": "수정된 그룹명",
  "img": "https://example.com/updated-group.jpg",
  "description": "그룹 설명 수정",
  "isPublic": false,
  "password": "family5678"
}

### 3. 그룹 삭제
DELETE http://localhost:3000/api/groups/5
Content-Type: application/json

{
  "password": "group1234"
}

### 4. 그룹 목록 조회
GET http://localhost:3000/api/groups

### 5. 그룹 상세 조회
### 5-1. 그룹의 공개/비공개 여부 조회
GET http://localhost:3000/api/groups/66fe495af847596339501bcb/is-public

### 5-2-1. 상세조회(공개그룹)
GET http://localhost:3000/api/groups/2
### 5-2-2. 상세조회(비공개그룹)
GET http://localhost:3000/api/groups/3/verify-password
### 5-3. 공감 보내기 버튼
POST http://localhost:3000/api/groups/66fe495af847596339501bcb/like


### 게시글
### 1. 게시글 등록
POST http://localhost:3000/api/groups/66fe567a2c7961fe669fed5d/posts
Content-Type: application/json

{ 
  "nickname": "철수",
  "title": "새로운 추억",
  "img": "https://example.com/new-memory.jpg",
  "description": "추억의 순간",
  "tags": ["추억", "여행"],
  "place": "서울",
  "isPublic": true,
  "password": "post1234"
}

### 2. 게시글 수정
PUT http://localhost:3000/api/posts/1
Content-Type: application/json

{
  "title": "수정된 추억",
  "description": "추억의 순간 수정",
  "tags": ["수정된 태그"],
  "isPublic": false,
  "password": "post1234"
}

### 3. 게시글 삭제
DELETE http://localhost:3000/api/groups/66fe567a2c7961fe669fed5d/posts/1
Content-Type: application/json

{
  "password": "post1234"
}

### 4. 게시글 목록 조회
GET http://localhost:3000/api/groups/66fe567a2c7961fe669fed5d/posts

###
GET http://localhost:3000/api/posts


### 4-1. 게시글 공개 여부 확인
GET http://localhost:3000/api/posts/1/is-public

### 5. 게시글 상세 조회
GET http://localhost:3000/api/posts/1

### 5-1. 공감 보내기 버튼
POST http://localhost:3000/api/posts/1/like

### 댓글
### 1. 댓글 등록
POST http://localhost:3000/api/posts/1/comments
Content-Type: application/json

{ 
  "id": 1,
  "nickname": "철수",
  "commentcontent": "좋은 추억이네요!",
  "password": "comment1234"
}

### 2. 댓글 수정
PUT http://localhost:3000/api/comments/1
Content-Type: application/json

{
  "commentcontent": "수정된 댓글 내용",
  "password": "comment1234"
}

### 3. 댓글 삭제
DELETE http://localhost:3000/api/comments/1
Content-Type: application/json

{
  "password": "comment1234"
}

### 4. 댓글 목록 조회
GET http://localhost:3000/api/posts/1/comments
